sudo: required
services:
  - docker
node_js:
  - "11.10.1"

before_install:
  - docker build -t dayhunter/docker-react -f Dockerfile.dev .

script:
  - docker run dayhunter/docker-react npm run test -- --coverage